# Generated by Django 4.2.4 on 2023-08-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_articles_alter_beehiivarticles_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeehiivArticles',
        ),
    ]
