# Generated by Django 4.2.4 on 2023-08-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_beehiivarticles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Newsletters',
        ),
    ]
